### ISSUE TITLE
On the Add Facility form, scroll to the top of the page after the user submits the form.

### ISSUE THREAD

**Issue by mmnavarr** [providermap/provider-map-client#22]
On the Add Facility form, scroll to the top of the page after the user submits the form.

The reason for this is that on small viewports, the notification toast at the top may be hidden when the user submits.

**Comment by CodingApps** [comment]
I'd like to add the scroll-to-top for this page.

**Comment by mmnavarr** [comment]
@CodingApps by all means, give it a try!
